services:
  bot:
    image: localhost:5000/assistant-bot:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data/:/app/data

  redis:
    image: redis:8.4
    restart: always
    ports:
      - "6379"
    command: redis-server --loglevel verbose --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
